package com.example.englishapp.BatQuiTac

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import com.example.englishapp.Database.BLDongTuBQT
import com.example.englishapp.Database.BLTuMoi



class AllBatQuiTac(context: Context?, name: String?, factory: SQLiteDatabase.CursorFactory?, version: Int
) : BLDongTuBQT(context, name, factory, version) {
    fun add()
    {
        Insert_batquitac("abide","abode ","abode ","lưu trú, lưu lại")
        Insert_batquitac("arise","arose","arisen","phát sinh")
        Insert_batquitac("awake","awoke","awoken","đánh thức,thức")
        Insert_batquitac("backslide","backslid","backslidden","tái phạm")
        Insert_batquitac("be","was/were","been","thì, là, bị, ở")
        Insert_batquitac("bear","bore","borne","mang, chịu đựng")
        Insert_batquitac("beat","beat","beaten","đánh, đập")
        Insert_batquitac("become","became","become","trở nên")
        Insert_batquitac("befall","befell","befallen","xảy đến")
        Insert_batquitac("begin","began","begun","bắt đầu")
        Insert_batquitac("behold","beheld","beheld","ngắm nhìn")
        Insert_batquitac("bend","bent","bent","bẻ cong")
        Insert_batquitac("beset","beset","beset","bao quanh")
        Insert_batquitac("bespeak","bespoke","bespoken","chứng tỏ")
        Insert_batquitac("bet","bet","bet","đánh cược, cá cược")
        Insert_batquitac("bid","bid","bid","trả giá")
        Insert_batquitac("bind","bound","bound","buộc, trói")
        Insert_batquitac("bite","bit","bitten","cắn")
        Insert_batquitac("bleed","bled","bled","chảy máu")
        Insert_batquitac("blow","blew","blown","thổi")
        Insert_batquitac("break","broke","broken","đập  vỡ")
        Insert_batquitac("breed","bred","bred","nuôi,dạy dỗ")
        Insert_batquitac("bring","brought","brought","mang đến")
        Insert_batquitac("broadcast","broadcast","broadcast","phát thanh")
        Insert_batquitac("browbeat","browbeat","browbeaten\nbrowbeat","hăm dọa")
        Insert_batquitac("build","built","built","xây dựng")
        Insert_batquitac("burn","burnt\nburned","burnt\nburned","đốt, cháy")
        Insert_batquitac("burst","burst","burst","nổ tung, vỡ òa")
        Insert_batquitac("bust","busted\nbust","busted\nbust","làmbể, làmvỡ")
        Insert_batquitac("buy","bought","bought","mua")
        Insert_batquitac("cast","cast","cast", "tung")
        Insert_batquitac("catch","caught","caught","bắt, chụp")
        Insert_batquitac("chide","chid\nchided","chid\nchidden\nchided","mắng, chửi")
        Insert_batquitac("choose","chose","chosen","chọn, lựa")
        Insert_batquitac("cleave","clove\ncleft\ncleaved","cloven\ncleft\ncleaved","chẻ, táchhai")
        Insert_batquitac("cling","clung","clung","bámvào, dínhvào")
        Insert_batquitac("come","came","come","đến, đi đến")
        Insert_batquitac("creep","crept","crept","bò, trườn, lẻn")
        Insert_batquitac("crow","crew\ncrewed","crowed","gáy(gà)")
        Insert_batquitac("daydream","daydreamed\ndaydreamt","daydreamed\ndaydreamt","nghĩ vẩn")
        Insert_batquitac("deal","dealt","dealt","giao thiệp")
        Insert_batquitac("dig","dug","dug","đào")
        Insert_batquitac("disprove","disproved","disproved\ndisproven","bác bỏ")
        Insert_batquitac("dive","dove\ndived","dived","lặn, lao xuống")
        Insert_batquitac("do","did","done","làm")
        Insert_batquitac("draw","drew","drawn","vẽ, kéo")
        Insert_batquitac("dream","dreamt\ndreamed","dreamt\ndreamed","mơ thấy")
        Insert_batquitac("drink","drank","drunk","uống")
        Insert_batquitac("drive","drove","driven","lá ixe")
        Insert_batquitac("eat","ate","eaten","ăn")
        Insert_batquitac("fall","fell","fallen","ngã, rơi")
        Insert_batquitac("feed","fed","fed","choăn, ăn, nuôi")
        Insert_batquitac("feel","felt","felt","cảm thấy")
        Insert_batquitac("fight","fought","fought","chiến đấu")
        Insert_batquitac("find","found","found","tìm thấy ,thấy")
        Insert_batquitac("flee","fled","fled","chạy trốn")
        Insert_batquitac("fling","flung","flung","tung, quăng")
        Insert_batquitac("freeze","froze","frozen","(làm) đônglại")
        Insert_batquitac("get","got","got\ngotten","cóđược")
        Insert_batquitac("gild","gilt\ngilded","gilt\ngilded","mạ vàng")
        Insert_batquitac("gird","girt\ngirded","girt\ngirded","đeo vào")
        Insert_batquitac("give","gave","given","cho")
        Insert_batquitac("go","went","gone","đi")
        Insert_batquitac("grind","ground","ground","nghiền, xay")
        Insert_batquitac("grow","grew","grown","mọc, trồng")
        Insert_batquitac("hand-feed","hand-fed","hand-fed","choăn  bằng tay")
        Insert_batquitac("handwrite","handwrote","handwritten","viết tay")
        Insert_batquitac("hang","hung","hung","móc lên, treo lên")
        Insert_batquitac("have","had","had","có")
        Insert_batquitac("hear","heard","heard","nghe")
        Insert_batquitac("heave","hove\nheaved","hove, heaved","trục lên")
        Insert_batquitac("hew","hewed","hewn\nhewed","chặt, đốn")
        Insert_batquitac("hide","hid","hidden","giấu, trốn, nấp")
        Insert_batquitac("inbreed","inbred","inbred","lai giống, cận huyết")
        Insert_batquitac("inlay","inlaid","inlaid","cẩn, khảm")
        Insert_batquitac("input","input","input","đưa vào")
        Insert_batquitac("interbreed","interbred","interbred","giao phối,lai giống")
        Insert_batquitac("interwind","interwound","interwound","cuộn vào,quấn vào")
        Insert_batquitac("keep","kept","kept","giữ")
        Insert_batquitac("know","knew","known","biết, quen biết")
        Insert_batquitac("lay","laid","laid","đặt, để")
        Insert_batquitac("learn","learnt\nlearned","learnt\nlearned","học, được biết")
        Insert_batquitac("leave","left","left","ra đi, đểlại")
        Insert_batquitac("lend","lent","lent","cho mượn")
        Insert_batquitac("light","lit/lighted","lit/lighted","thắp sáng")
        Insert_batquitac("lose","lost","lost","làm  mất, mất")
        Insert_batquitac("make","made","made","chếtạo,\nsản xuất")
        Insert_batquitac("mean","meant","meant","có nghĩa là")
        Insert_batquitac("meet","met","met","gặp mặt")
        Insert_batquitac("misspeak","misspoke","misspoken","nói sai")
        Insert_batquitac("outlie","outlied","outlied","nói dối")
        Insert_batquitac("outsit","outsat","outsat","ngồi lâu hơn")
        Insert_batquitac("pay","paid","paid","trả(tiền)")
        Insert_batquitac("plead","pleaded\npled","pleaded\npled","bào chữa, biện hộ")
        Insert_batquitac("rend","rent","rent","toạc ra, xé")
        Insert_batquitac("ride","rode","ridden","cưỡi")
        Insert_batquitac("ring","rang","rung","rung chuông")
        Insert_batquitac("rise","rose","risen","đứng dậy, mọc")
        Insert_batquitac("run","ran","run","chạy")
        Insert_batquitac("saw","sawed","sawn","cưa")
        Insert_batquitac("say","said","said","nói")
        Insert_batquitac("see","saw","seen","nhìn thấy")
        Insert_batquitac("seek","sought","sought","tìmkiếm")
        Insert_batquitac("sell","sold","sold","bán")
        Insert_batquitac("send","sent","sent","gửi")
        Insert_batquitac("shake","shook","shaken","lay, lắc")
        Insert_batquitac("shine","shone","shone","chiếu sáng")
        Insert_batquitac("shoot","shot","shot","bắn")
        Insert_batquitac("sing","sang","sung","ca hát")
        Insert_batquitac("sink","sank","sunk","chìm, lặn")
        Insert_batquitac("sit","sat","sat","ngồi")
        Insert_batquitac("slay","slew","slain","sá thại,\ngiết hại")
        Insert_batquitac("sleep","slept","slept","ngủ")
        Insert_batquitac("slide","slid","slid","trượt, lướt")
        Insert_batquitac("sling","slung","slung","ném mạnh")
        Insert_batquitac("smite","smote","smitten","đập mạnh")
        Insert_batquitac("speak","spoke","spoken","nói")
        Insert_batquitac("spend","spent","spent","tiêu xài")
        Insert_batquitac("steal","stole","stolen","đánh cắp")
        Insert_batquitac("take","took","taken","cầm, lấy")
        Insert_batquitac("teach","taught","taught","dạy, giảng dạy")
        Insert_batquitac("tell","told","told","kể, bảo")
        Insert_batquitac("think","thought","thought","suy nghĩ")
        Insert_batquitac("wake","woke\nwaked","woken\nwaked","thức giấc")
        Insert_batquitac("wear","wore","worn","mặc")
        Insert_batquitac("weep","wept","wept","khóc")
        Insert_batquitac("win","won","won","thắng, chiến thắng")
        Insert_batquitac("wind","wound","wound","quấn")
        Insert_batquitac("write","wrote","written","viết")


    }

}